version: '3.8'
services:
    api:
        build:
            dockerfile: Dockerfile
            context: ./app
        image:
            'nikhiltiru/py_backend_sandbox:${TAG}'
        env_file:
            - .env
        environment:
            - TEST_ENV=test
        ports:
            - ${HOST_PORT}:${CONT_PORT}
        # expose:
        #     - ${HOST_PORT}
