FROM python:3.8-buster

# Set application working directory
WORKDIR /usr/src/app

# Install requirements
COPY requirements_dev.txt ./
RUN pip install --no-cache-dir -r requirements_dev.txt

# Install application
# COPY . .

# Run application
# CMD ["uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "${CONT_PORT}"]
CMD uvicorn app:app --reload --host 0.0.0.0 --port $CONT_PORT
